services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    # 保持容器運行，防止啟動後立即退出
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/workspace
      - PYTHONDONTWRITEBYTECODE=1 # 不產生 __pycache__