services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8810:5000"
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
